# Include files <file.h> dependencies for joe files

UgpWithCvCompFlow_H = $(JOE_HOME)/joe/include/UgpWithCvCompFlow.h \
                      $(MiscUtils_H)       \
                      $(tc_vec3d_H)        \
                      $(UgpWithCv2_H)      \
                      $(MshFilter_H)       \
                      $(Param_H)           \
                      $(AtmosphericCond_H) \
                      $(PetscSolver_H)

JoeWithModels_H = $(JOE_HOME)/joe/include/JoeWithModels.h \
                  $(UgpWithCvCompFlow_H)

UgpWithCvCompFlowAD_H = $(JOE_HOME)/joe/include/UgpWithCvCompFlowAD.h \
                        $(UgpWithCvCompFlow_H)

JoeWithModelsAD_H = $(JOE_HOME)/joe/include/JoeWithModelsAD.h \
                    $(UgpWithCvCompFlowAD_H)

joe_H = $(JoeWithModels_H)
